# Service Config
SERVICE_HOST = "0.0.0.0"
SERVICE_PORT = 9030
TOKEN_EXPIRES = 14400
SECRET_KEY="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"

# Database Config
MARIADB_HOST = "127.0.0.1"
MARIADB_PORT = 3306
MARIADB_NAME = "xface_system"
