username = "admin"
host = "172.21.100.174"
port = 9082
database = {user='root', password='root', host='172.21.100.174', port=3306, database_name='xface_system'}
redis_db = {host='localhost', port=6379}
expires = 14400