
SERVICE_HOST = "0.0.0.0"
SERVICE_PORT = 9082
TOKEN_EXPIRES = 14400
SECRET_KEY="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"

MARIADB_HOST = "172.21.100.174"
MARIADB_PORT = 3306
MARIADB_NAME = "xface_system"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_PASSWORD = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"

